# Generated by Django 2.2.5 on 2019-10-14 07:55

from django.db import migrations, models
import instaposter.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to=instaposter.utils.load_image)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
