# Generated by Django 2.2.6 on 2019-10-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaposter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
