# Generated by Django 2.2.7 on 2020-03-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_poster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citypost',
            name='header',
            field=models.CharField(default='', max_length=255, verbose_name='Название конфигурации'),
        ),
    ]
