# Generated by Django 2.2.7 on 2020-03-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_poster', '0002_citypost_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=255, verbose_name='Название конфигурации')),
                ('city', models.BooleanField(default=True, verbose_name='Город')),
                ('title', models.BooleanField(default=True, verbose_name='Название')),
                ('text', models.BooleanField(default=True, verbose_name='Описание')),
                ('image', models.BooleanField(default=True, verbose_name='Фотография достопримечательности')),
                ('coordinates', models.BooleanField(verbose_name='Координаты')),
                ('latitude', models.BooleanField(verbose_name='Широта')),
                ('longitude', models.BooleanField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Пост достопримечательности',
                'verbose_name_plural': 'Посты достопримечтельностей',
            },
        ),
    ]
