# Generated by Django 2.2.7 on 2020-03-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_poster', '0003_sight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sight',
            new_name='SightPost',
        ),
    ]
