# Generated by Django 2.2.7 on 2020-03-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_poster', '0005_citytrippost'),
    ]

    operations = [
        migrations.AddField(
            model_name='citypost',
            name='hashtags',
            field=models.BooleanField(default=True, verbose_name='Хэштэги'),
        ),
    ]
