# Generated by Django 2.2.7 on 2020-01-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20200122_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='video_picture',
            field=models.ImageField(default='image/v1.jpg', upload_to='images/video_pics/', verbose_name='Превью видео'),
        ),
    ]
