# Generated by Django 2.2.7 on 2020-01-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20200122_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='main_banner',
            field=models.ImageField(upload_to='images/banners/', verbose_name='Баннер'),
        ),
    ]
