# Generated by Django 2.2.7 on 2020-02-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20200123_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='center_social_url',
            field=models.CharField(default='', max_length=255, verbose_name='Центральная ссылка на социальные сети'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='left_social_url',
            field=models.CharField(default='', max_length=255, verbose_name='Левая ссылка на социальные сети'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='right_social_url',
            field=models.CharField(default='', max_length=255, verbose_name='Правая ссылка на социальные сети'),
        ),
    ]
