# Generated by Django 2.2.7 on 2020-03-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20200214_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['title'], 'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
    ]
