# Generated by Django 2.2.5 on 2019-09-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0002_auto_20190906_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteBySights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название маршрута')),
                ('sights', models.ManyToManyField(to='geography.Sight', verbose_name='Достопримечательности маршрута')),
            ],
            options={
                'verbose_name': 'Маршрут по достопримечательностям',
                'verbose_name_plural': 'Маршруты по достопримечательностям',
            },
        ),
        migrations.CreateModel(
            name='RouteByCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название маршрута')),
                ('cities', models.ManyToManyField(to='geography.City', verbose_name='Города маршрута')),
            ],
            options={
                'verbose_name': 'Маршрут по городам',
                'verbose_name_plural': 'Маршруты по городам',
            },
        ),
    ]
