# Generated by Django 2.2.6 on 2019-10-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citiesrelationship',
            unique_together={('route', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='sightsrelationship',
            unique_together={('route', 'position')},
        ),
    ]
