# Generated by Django 2.2.5 on 2019-10-04 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0006_auto_20190927_1331'),
        ('traces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityInRoute',
            fields=[
                ('city_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geography.City')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            bases=('geography.city',),
        ),
        migrations.AlterField(
            model_name='routebycities',
            name='cities',
            field=models.ManyToManyField(to='traces.CityInRoute', verbose_name='Города маршрута'),
        ),
        migrations.AddField(
            model_name='cityinroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traces.RouteByCities'),
        ),
        migrations.AlterUniqueTogether(
            name='cityinroute',
            unique_together={('route', 'position')},
        ),
    ]
