# Generated by Django 2.2.7 on 2019-12-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0002_auto_20191014_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routebycities',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='routebysights',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
