# Generated by Django 2.2.5 on 2019-10-04 08:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0006_auto_20190927_1331'),
        ('traces', '0002_auto_20191004_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routebycities',
            name='cities',
        ),
        migrations.AddField(
            model_name='routebycities',
            name='cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='CityInRoute',
        ),
    ]
