# Generated by Django 2.2.5 on 2019-10-04 08:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0004_auto_20191004_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='routebycities',
            name='positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
    ]
