# Generated by Django 2.2.5 on 2019-10-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0006_auto_20190927_1331'),
        ('traces', '0005_routebycities_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routebycities',
            name='positions',
        ),
        migrations.AlterField(
            model_name='routebycities',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='cities_in_route', to='geography.City'),
        ),
        migrations.DeleteModel(
            name='CityInRoute',
        ),
    ]
