# Generated by Django 2.2.5 on 2019-10-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0010_auto_20191008_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routebycities',
            name='description',
        ),
        migrations.RemoveField(
            model_name='routebysights',
            name='description',
        ),
        migrations.AlterField(
            model_name='routebysights',
            name='sights',
            field=models.ManyToManyField(to='geography.Sight', verbose_name='Достопримечательности маршрута'),
        ),
        migrations.DeleteModel(
            name='SightsRelationship',
        ),
    ]
