# Generated by Django 2.2.5 on 2019-10-08 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0011_merge_20191008_1259'),
        ('traces', '0011_auto_20191008_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightsRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='routebycities',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='routebysights',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='routebysights',
            name='sights',
            field=models.ManyToManyField(through='traces.SightsRelationship', to='geography.Sight', verbose_name='Достопримечательности маршрута'),
        ),
        migrations.AddField(
            model_name='sightsrelationship',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traces.RouteBySights'),
        ),
        migrations.AddField(
            model_name='sightsrelationship',
            name='sight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.Sight'),
        ),
    ]
