# Generated by Django 2.2.7 on 2020-01-23 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traces', '0003_auto_20191204_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateTimeField(verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Путешественник',
                'verbose_name_plural': 'Путешественники',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название путешествия')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала путешествия')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания путешествия')),
                ('description', models.TextField(default='', verbose_name='Описание путешествия')),
                ('route_by_cities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_route_city', to='traces.RouteByCities', verbose_name='Путешествие по маршрутам городов')),
                ('route_by_sights', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_route_sight', to='traces.RouteBySights', verbose_name='Путешествие по маршрутам достопримечательностей')),
                ('traveler', models.ManyToManyField(related_name='trip_traveler', to='trips.Traveler', verbose_name='Путешественники')),
            ],
            options={
                'verbose_name': 'Путешествие',
                'verbose_name_plural': 'Путешествия',
                'ordering': ['title'],
            },
        ),
    ]
