# Generated by Django 2.2.7 on 2020-01-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0003_auto_20191204_0944'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название путешествия')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала путешествия')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания путешествия')),
                ('description', models.TextField(default='', verbose_name='Описание путешествия')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_route_city', to='traces.RouteByCities', verbose_name='Путешествие по маршрутам городов')),
                ('traveler', models.ManyToManyField(related_name='city_trip_traveler', to='trips.Traveler', verbose_name='Путешественники')),
            ],
            options={
                'verbose_name': 'Путешествие городам',
                'verbose_name_plural': 'Путешествия по городам',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SightTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название путешествия')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала путешествия')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания путешествия')),
                ('description', models.TextField(default='', verbose_name='Описание путешествия')),
                ('route_by_sights', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_route_sight', to='traces.RouteBySights', verbose_name='Путешествие по маршрутам достопримечательностей')),
                ('traveler', models.ManyToManyField(related_name='sight_trip_traveler', to='trips.Traveler', verbose_name='Путешественники')),
            ],
            options={
                'verbose_name': 'Путешествие по достопримечательностям',
                'verbose_name_plural': 'Путешествия по достопримечательностям',
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
