# Generated by Django 2.2.7 on 2020-01-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20200123_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveler',
            options={'ordering': ['last_name'], 'verbose_name': 'Путешественник', 'verbose_name_plural': 'Путешественники'},
        ),
        migrations.AddField(
            model_name='traveler',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия'),
        ),
    ]
