# Generated by Django 2.2.7 on 2020-01-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20200123_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveler',
            options={'verbose_name': 'Путешественник', 'verbose_name_plural': 'Путешественники'},
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='last_name',
        ),
    ]
