# Generated by Django 2.2.7 on 2020-01-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20200123_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytrip',
            name='traveler',
            field=models.ManyToManyField(to='trips.Traveler', verbose_name='Путешественники'),
        ),
        migrations.AlterField(
            model_name='sighttrip',
            name='traveler',
            field=models.ManyToManyField(to='trips.Traveler', verbose_name='Путешественники'),
        ),
    ]
