# Generated by Django 2.2.5 on 2019-09-04 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок')),
                ('link', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Ссылка')),
                ('text', models.TextField(default='', verbose_name='Текст')),
                ('coordinates', models.CharField(blank=True, default='', max_length=100, verbose_name='Координаты')),
                ('posted', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('sight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.Sight', verbose_name='Достопримечательность')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(db_index=True, default='', max_length=255, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Имя')),
                ('link', models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='Ссылка')),
                ('photo', models.CharField(default='http://gpsnew.ru/images/products/no_picture.jpg', max_length=255, verbose_name='Фото')),
                ('sourses', models.ManyToManyField(to='travelers.Source', verbose_name='Источники')),
            ],
            options={
                'verbose_name': 'Путешественник',
                'verbose_name_plural': 'Путешественники',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
                ('tag', models.CharField(blank=True, default='', max_length=255, verbose_name='Тэг')),
                ('photo', models.CharField(default='', max_length=255, verbose_name='Фото')),
                ('city', models.CharField(default='', max_length=255, verbose_name='Город')),
                ('sourses', models.ManyToManyField(to='travelers.Source', verbose_name='Источники')),
                ('travelers', models.ManyToManyField(to='travelers.Traveler', verbose_name='Путешественники')),
            ],
            options={
                'verbose_name': 'Путешествие',
                'verbose_name_plural': 'Путешествия',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=50, verbose_name='Тэг')),
                ('post', models.ManyToManyField(to='travelers.Post', verbose_name='Посты')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.City', verbose_name='Город')),
                ('places', models.ManyToManyField(to='geography.Sight', verbose_name='Места')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='', upload_to='images/photo/', verbose_name='Изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelers.Post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Фотография отзыва',
                'verbose_name_plural': 'Фотографии отзыва',
            },
        ),
    ]
