# Generated by Django 2.2.5 on 2019-09-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveler',
            old_name='sourses',
            new_name='sources',
        ),
    ]
