# Generated by Django 2.2.5 on 2019-09-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0002_auto_20190905_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postphoto',
            name='post',
        ),
        migrations.RemoveField(
            model_name='route',
            name='city',
        ),
        migrations.RemoveField(
            model_name='route',
            name='places',
        ),
        migrations.RemoveField(
            model_name='route',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='sourses',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='travelers',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='sources',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostPhoto',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
        migrations.DeleteModel(
            name='Traveler',
        ),
    ]
