# Generated by Django 2.2.5 on 2019-10-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.PositiveIntegerField(default=0, null=True)),
                ('owner_id', models.PositiveIntegerField(default=0, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
            ],
        ),
    ]
