# Generated by Django 2.2.5 on 2019-10-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='upload_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='vk_id',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
