# Generated by Django 2.2.5 on 2019-10-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0004_auto_20191003_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
