# Generated by Django 2.2.5 on 2019-10-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0005_auto_20191003_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='vk_id',
            field=models.PositiveIntegerField(default=0, null=True, unique=True),
        ),
    ]
