# Generated by Django 2.2.5 on 2019-10-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0006_auto_20191003_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='vk_id',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('vk_id', 'owner_id')},
        ),
    ]
