# Generated by Django 2.2.5 on 2019-10-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkapp', '0007_auto_20191003_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='upload_time',
            new_name='date',
        ),
    ]
