# Generated by Django 2.2.5 on 2019-10-09 09:56

from django.db import migrations, models
import django.db.models.deletion
import geography.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, verbose_name='Адрес')),
                ('image', models.FileField(blank=True, null=True, upload_to=geography.models.image_city, verbose_name='Изображение')),
                ('default_zoom', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Масштаб')),
                ('centre_coordinates', models.CharField(blank=True, default='', max_length=100, verbose_name='Координаты')),
                ('posted', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('show_on_mainmap', models.BooleanField(default=True, verbose_name='Показывать на главной карте')),
                ('regional_center', models.BooleanField(default=True, verbose_name='Региональный центр')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения')),
                ('autotravel_url', models.CharField(blank=True, default='', max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('image', models.FileField(blank=True, null=True, upload_to=geography.models.image_region, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('text', models.TextField(default='', verbose_name='Описание')),
                ('image', models.FileField(blank=True, max_length=200, null=True, upload_to=geography.models.image_sight, verbose_name='Фотография достопримечательности')),
                ('original_coordinates', models.CharField(blank=True, default='', max_length=100, verbose_name='Стянутные координаты')),
                ('coordinates', models.CharField(blank=True, default='', max_length=100, verbose_name='Координаты')),
                ('posted', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('regional', models.BooleanField(default=False, verbose_name='В регионе')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('fix_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата исправления')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес')),
                ('autotravel_url', models.CharField(blank=True, default='', max_length=255, verbose_name='URL')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sight', to='geography.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечтельности',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfSights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('time', models.CharField(blank=True, default='', max_length=100, verbose_name='Время')),
                ('color', models.CharField(default='#0000FF', max_length=30, verbose_name='Цвет')),
                ('marker', models.CharField(default='marks/flag-export.png', max_length=30, verbose_name='Маркер')),
            ],
            options={
                'verbose_name': 'Тип достопримечательности',
                'verbose_name_plural': 'Типы достопримечательностей',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SightPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default='', max_length=200, upload_to=geography.models.image_sight, verbose_name='Изображение')),
                ('posted', models.BooleanField(default=True)),
                ('sight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sight_photo', to='geography.Sight', verbose_name='Достпримечательность')),
            ],
            options={
                'verbose_name': 'Фотография достопримечательности',
                'verbose_name_plural': 'Фотографии достопримечательности',
            },
        ),
        migrations.AddField(
            model_name='sight',
            name='type',
            field=models.ManyToManyField(related_name='type_sight', to='geography.TypeOfSights', verbose_name='Достопримечательности'),
        ),
        migrations.CreateModel(
            name='SectionOfSights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('types', models.ManyToManyField(blank=True, related_name='type_section_of_sights', to='geography.TypeOfSights', verbose_name='Типы')),
            ],
            options={
                'verbose_name': 'Раздел достопримечательностей',
                'verbose_name_plural': 'Разделы достопримечательностей',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='geography.Region', verbose_name='Регион'),
        ),
    ]
