# Generated by Django 2.2.6 on 2019-10-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='sight',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Долгота'),
        ),
    ]
