# Generated by Django 2.2.6 on 2019-10-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_auto_20191014_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Долгота'),
        ),
    ]
