# Generated by Django 2.2.5 on 2019-09-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_auto_20190906_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightphoto',
            name='file',
            field=models.ImageField(default='', upload_to='photo/photo/', verbose_name='Изображение'),
        ),
    ]
