# Generated by Django 2.2.5 on 2019-09-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_auto_20190906_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='photo/cities/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='photo/regions/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sight', to='geography.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='sightphoto',
            name='file',
            field=models.ImageField(default='', upload_to='photo/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sightphoto',
            name='sight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sight_photo', to='geography.Sight', verbose_name='Достпримечательность'),
        ),
    ]
