# Generated by Django 2.2.5 on 2019-09-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_auto_20190909_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='show_on_mainmap',
            field=models.BooleanField(verbose_name='Показывать на главной карте'),
        ),
    ]
