# Generated by Django 2.2.6 on 2019-11-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_auto_20191021_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='rating',
            field=models.SmallIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
