# Generated by Django 2.2.6 on 2019-11-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0005_auto_20191112_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightphoto',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
        ),
    ]
