# Generated by Django 2.2.5 on 2019-10-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0006_auto_20190927_1331'),
        ('geography', '0006_auto_20190927_1241'),
    ]

    operations = [
    ]
