# Generated by Django 2.2.5 on 2019-10-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0007_merge_20191007_0625'),
        ('geography', '0007_merge_20191004_1107'),
    ]

    operations = [
    ]
