# Generated by Django 2.2.5 on 2019-10-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0009_auto_20191007_1351'),
        ('geography', '0008_merge_20191007_1316'),
    ]

    operations = [
    ]
