# Generated by Django 2.2.5 on 2019-10-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0010_merge_20191008_0709'),
        ('geography', '0010_auto_20191008_1250'),
    ]

    operations = [
    ]
